/**
 * BootScene — Preloads assets before the game starts.
 *
 * Loads the tileset PNG and Tiled JSON map that D has already delivered.
 * Character sprites are loaded later when D provides them; for now we use
 * placeholder graphics (coloured rectangles) in the entity classes.
 */

import Phaser from "phaser";

/** Tile size in pixels; tileset dimensions must align to this grid. */
const TILE_SIZE = 32;

export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: "BootScene" });
  }

  preload(): void {
    const { width, height } = this.cameras.main;

    // --- Loading bar UI ---
    const loadingText = this.add
      .text(width / 2, height / 2 - 10, "Loading...", {
        fontSize: "24px",
        color: "#ffffff",
      })
      .setOrigin(0.5);

    const barW = 320;
    const barH = 20;
    const barBg = this.add.rectangle(
      width / 2,
      height / 2 + 30,
      barW,
      barH,
      0x333333,
    );
    const barFill = this.add.rectangle(
      width / 2 - barW / 2,
      height / 2 + 30,
      0,
      barH,
      0x4caf50,
    );
    barFill.setOrigin(0, 0.5);

    this.load.on("progress", (value: number) => {
      barFill.width = barW * value;
    });

    this.load.on("complete", () => {
      loadingText.destroy();
      barBg.destroy();
      barFill.destroy();
    });

    // --- Real assets from D ---
    // Tileset image generated by scripts/generate-building-tiles.mjs
    this.load.image("campus-tileset", "assets/tilesets/campus-tileset.png");

    // Tiled map JSON (200×150 tiles = 6400×4800 px world)
    this.load.tilemapTiledJSON("campus-test", "assets/maps/campus-test.json");

    // TODO: load avatar spritesheets and NPC sprites when D delivers them
    // this.load.spritesheet("avatar_01", "assets/sprites/avatars/avatar_01.png", {
    //   frameWidth: 32,
    //   frameHeight: 48,
    // });
  }

  create(): void {
    // Verify the tileset still aligns with the 32x32 tile grid.
    const tex = this.textures.get("campus-tileset").getSourceImage();
    if (
      tex.width % TILE_SIZE !== 0 ||
      tex.height % TILE_SIZE !== 0
    ) {
      console.warn(
        `[BootScene] Tileset size ${tex.width}×${tex.height} is not aligned to ${TILE_SIZE}×${TILE_SIZE} tiles.`,
      );
    }

    this.scene.start("GameScene");
  }
}
